//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManage.UI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StoreManagementEntities : DbContext
    {
        public StoreManagementEntities()
            : base("name=StoreManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuthUser> AuthUsers { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Customers> Customers1 { get; set; }
        public virtual DbSet<Orders> Orders1 { get; set; }
        public virtual DbSet<OrderStatus> OrderStatus1 { get; set; }
        public virtual DbSet<Products> Products1 { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<UserPermissions> UserPermissions1 { get; set; }
    }
}
